on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

name: McCormick Observatory weather update

jobs:
  render:
    name: Update graphs
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          # use Posit's CRAN mirror with precompiled binaries
          use-public-rspm: true
          
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2 # automatically sets up cache
        with:
          packages: |
            any::ggplot2 
            any::cowplot
            any::readr
            any::tidyr
            any::dplyr
            any::lubridate
            any::stringr
            any::ggrepel
            any::scales
            any::here
            any::data.table
            any::R.utils
      
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Retrieve data
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 30
          max_attempts: 3
          command: Rscript -e 'source("R/Retrieve_GHCN_USC00441593.R")'
          continue_on_error: true
        
      - name: Build temperature graph
        run:  Rscript -e 'source("R/NewMultiYearTemp.R")'
    # Creates CombinedTemp_LMO_YYYY.png graphs
    
      - name: Build annual precipitation graph, previous years
        run:  Rscript -e 'source("R/MultiYearPrecip.R")'
    # Creates Precip_YYYY.png graphs
    
      - name: Build current year precip graph
        run: Rscript -e 'source("R/BuildCumulativePrecipitation.R")'
    # Creates Precip_YYYY.png graph (for this year)
    
      - name: Annual Temperature graph
        run: Rscript -e 'source("R/AnnualTemp.R")'
    # Creates AnnualTemperatureTrends.png graph
        
      - name: Commit graphs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update data & graphs
